version: '3'

services:
    haproxy:
        container_name: "sugar-haproxy"
        image: sugar-haproxy
        build: ../../build/haproxy/
        ports:
            - "80:80"
            - "443:443"
            - "127.0.0.1:54321:54321"
        networks:
            - sugar-network
        depends_on:
            - web1
    web1:
        container_name: "sugar-web1"
        image: sugar-web1
        build: ../../build/apache/
        ports:
            - "127.0.0.1:8080:8080"
        volumes:
            - ../../data/apache/sugar:/var/www/html/sugar
        networks:
            - sugar-network
        depends_on:
            - mysql
            - elasticsearch
            - redis
            - php
    php:
        container_name: "sugar-php-8.0"
        image: sugar-php-8.0
        build: ../../build/php/8.0/
        ports:
            - "127.0.0.1:9000:9000"
        volumes:
            - ../../data/apache/sugar:/var/www/html/sugar
        networks:
            - sugar-network
    mysql:
        container_name: "sugar-mysql-8"
        image: sugar-mysql-8
        build: ../../build/mysql/8.0/
        ports:
            - "127.0.0.1:3306:3306"
        volumes:
            - ../../data/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        networks:
            - sugar-network
    elasticserach:
        container_name: "sugar-elastic-7.16.3"
        image: sugar-elastic-7.16.3
        build: ../../build/elasticsearch/7.16.3/
        ports:
            - "127.0.0.1:9716:9716"
            - "127.0.0.1:9300:9300"
        environment:
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - discovery.type=single-node
            - http.port=9716
        volumes:
            - es-data:/usr/share/elasticsearch/data
        networks:
            - sugar-network
    redis:
        container_name: "sugar-redis"
        image: sugar-redis
        build: ../../build/redis/
        ports:
            - "127.0.0.1:6379:6379"
        volumes:
            - ../../data/redis:/data
        networks:
            - sugar-network

volumes:
    es-data:
        driver: local

networks:
    sugar-network:
        name: sugar-network 
        enable_ipv6: false
        driver: bridge
